### ISSUE TITLE
Feedback  JM

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/kdb#10]

**Comment by sashavor** [comment]
He has: 
-funding from the EU
-full-time ML researchers that he can dedicate to the project

I sent him more info about the project and we should schedule a more concrete call about logistics with Yoshua (hopefully next week)

**Comment by Vict0rSch** [comment]
any kind of conditions?

**Comment by sashavor** [comment]
TBD pending the discussion with Yoshua. They will probably want their name on the project or something, and that's his call... :woman_shrugging:
