### ISSUE TITLE
Map out sources of data and potential collaborators

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/kdb#104]

**Comment by mukkavilli** [comment]
https://swot.jpl.nasa.gov/
https://www.pik-potsdam.de/research/
https://ai.googleblog.com/2019/03/a-summary-of-google-flood-forecasting.html 
http://www.nsercfloodnet.ca/

<blockquote><div><strong><a href="https://swot.jpl.nasa.gov/">NASA SWOT - Home</a></strong></div><div>SWOT: NASA's first global survey of Earth's surface water, providing data for clean air and water, extreme events, and long-term environmental changes</div></blockquote>
<blockquote><img src="https://www.pik-potsdam.de/favicon.ico" width="48" align="right"><div><strong><a href="https://www.pik-potsdam.de/research/">Research — PIK Research Portal</a></strong></div></blockquote>
<blockquote><img src="http://2.bp.blogspot.com/-qRz-hnwUdY4/WulXSQ6Rv4I/AAAAAAAATvQ/shk7KsphA0c3E3nUMsDVASqYaH0PhLPNwCK4BGAYYCw/s1600/GoogleAI_logo_horizontal_color_rgb.png" width="48" align="right"><div><img src="//ai.googleblog.com/favicon.ico" height="14"> Google AI Blog</div><div><strong><a href="http://ai.googleblog.com/2019/03/a-summary-of-google-flood-forecasting.html">A Summary of the Google Flood Forecasting Meets Machine Learning Workshop</a></strong></div><div>Posted by Sella Nevo, Senior Software Engineer and Rainier Aliment, Program Manager     Recently, we hosted the Google Flood Forecasting Mee...</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="http://www.nsercfloodnet.ca/">Floodnet - NSERC Network - Enhanced flood forecasting and management capacity in Canada</a></strong></div><div>Floodnet - NSERC Network - enhanced flood forecasting and management capacity in Canada</div></blockquote>

**Comment by mukkavilli** [comment]
https://www.fathom.global

<blockquote><img src="https://uploads-ssl.webflow.com/5b1a5c7d151be01b1b704893/5b1a5c7d151be08b2d704a47_FAVICON-3232.jpg" width="48" align="right"><div><strong><a href="https://www.fathom.global/">Fathom flood risk analytics and intelligence</a></strong></div><div>Our mission at Fathom has been to create the most detailed, accurate and comprehensive flood risk map of the entire planet. This will transform risk assessment, planning decisions, emergency preparedness and disaster response.</div></blockquote>

**Comment by mukkavilli** [comment]
https://drmkc.jrc.ec.europa.eu/

<blockquote><div><strong><a href="https://drmkc.jrc.ec.europa.eu/">Overview - European Commission</a></strong></div><div>European Commission Disaster Risk Management Knowledge Centre: Enhancing the Knowledge base to support Disaster Risk Management
The DRMKC is a new Commission initiative on better knowledge and competence management for sounder EU policy making.</div></blockquote>
