### ISSUE TITLE
Reducing randomness among pairs - Synthetic Data

### ISSUE THREAD

**Issue by gcosne** [cc-ai/kdb#107]
**Difference among pair of non-flooded and flooded images**
We would like to reduce the randomness for the vegetation and everywhere but the ground.
![image (1)](https://user-images.githubusercontent.com/25148268/66132506-2c87ee00-e5c3-11e9-9ac3-275fa94f06cd.png)
![image](https://user-images.githubusercontent.com/25148268/66132509-2db91b00-e5c3-11e9-886e-224b174b1138.png)
![image (2)](https://user-images.githubusercontent.com/25148268/66132519-2f82de80-e5c3-11e9-940f-73cca78ea66f.png)

**Comment by Vahe987** [comment]
I can probably stop all movement by just putting timescale=0 (will test)
about the rest I don't really know what you call noise, how you get this images? 
is this on all of the paired images, or just couple of them?
thanks

**Comment by gcosne** [comment]
That would be a good thing to stop the movements: timescale = constant
These images are produced by computing the difference between a non-flooded and flooded image of the same scene.
This randomness has been observed on several of them (one is already enough to make the optimization harder..)

**Comment by Vahe987** [comment]
Ok, on the next set of images I'll consider your comments, thank you
however, one thing to try first, is to take the same image and calculated the difference, because I'm surprised that buildings has difference as well ... timescale = 0 will stop the movement, but buildings are not moving anyways ...
