### ISSUE TITLE
Fire or larger city?

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/kdb#112]
Leo's time is almost over, we need to agree on what we need the most: larger city to get more view-points or do we want to have a Fire dataset? Share your thoughts & opinions

**Comment by vict0rsch** [comment]
\+ keep in mind: leo's away this week and only has 2 more so we need to decide this week

**Comment by Vahe987** [comment]
if we are going to need a Fire dataset in the future, I suggest he works on Fire

**Comment by vict0rsch** [comment]
I'm not sure what's more pressing and if we'll be doing fire in the near future. If we decide not to move forward now with the fire, how long would it take you in the future, without Léo?

**Comment by Vahe987** [comment]
it's hard to estimate, maybe a month if I will work on it 1d/week, have to take a closer look to be more precise.
Also, there is no guarantee that I will be around in the future, let's say if you decide to work on fire in January for example …
Do you know when you may start working on fire?

**Comment by 51N84D** [comment]
If it's difficult/impossible to, in the future, get the option we forgo, I think choosing to get fire now makes more sense (assuming we are certain that we will eventually want to do fire). Though a larger city is more immediately applicable, its marginal utility is smaller in the long run

**Comment by sashavor** [comment]
I agree with Sun, fire for now and then we'll see if we need something else

**Comment by Vahe987** [comment]
ok, cool, so we will continue as planned if nobody else has different opinions, thanks
