### ISSUE TITLE
Tianyu's TODO list from April 13th 

### ISSUE THREAD

**Issue by tianyu-z** [cc-ai/kdb#119]
Checklist from April 6th

Notes
✅ means finished
❌ means canceled
❓ means questions here (ready to report on ML check) 

✅ Learning to Adapt Structured Output Space for Semantic Segmentation: arxiv.org/pdf/1802.10349.pdf

✅ ADVENT: Adversarial Entropy Minimization for Domain Adaptation in Semantic Segmentation: arxiv.org/pdf/1811.12833.pdf

✅ Domain Adaptation for Structured Output via Discriminative Patch Representations: arxiv.org/pdf/1901.05427v3.pdf

✅ DADA: Depth-aware Domain Adaptation in Semantic Segmentation: arxiv.org/abs/1904.01886

✅ Train a CycleGAN on the cluster

Checklist from April 13th

❓ Read the trainer.py code in MUNIT original repo

✅ Run the cycleGAN code with comet

✅ Play with the ADVENT repo in local machine

**Comment by vict0rsch** [comment]
It's great you've read all these ; now is there any one or two of these you'd like to discuss more in depth in a dedicated session where we'd have read the papers beforehand? 

What's your opinion on the best techniques so far?

**Comment by tianyu-z** [comment]
I will write a report today after I figure out my WIFI problem. I still got
some questions about the second paper. When I look up the notes, it's all
max entropy but the second one talks about min entropy. I need to do some
survey when I connect to the internet.

**Comment by tianyu-z** [comment]
Notes:

https://techn365-my.sharepoint.com/:w:/g/personal/admin_techn365_onmicrosoft_com/EQjH7dVe5RhFlqyrM09s38YBi-xewo36IvS_Pl2o1bJ4sw?e=huGo7x

<blockquote></blockquote>
