### ISSUE TITLE
Test SPADE model on segmented flood images

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/kdb#21]

**Comment by sashavor** [comment]
@pegahk has some initial results : https://elementai.slack.com/files/U6G4Y2XT6/FJFDG01T2/image.png 
She is working on improving them

<blockquote><img src="https://a.slack-edge.com/4a5c4/marketing/img/meta/favicon-32.png" width="48" align="right"><div><strong><a href="https://elementai.slack.com/files/U6G4Y2XT6/FJFDG01T2/image.png">Slack</a></strong></div></blockquote>

**Comment by sashavor** [comment]
Closing this for now, since SPADE invents buildings and that doesn't work for us
