### ISSUE TITLE
Emotional litterature review: what makes people change behaviors

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/kdb#28]

**Comment by jaswinder6991** [comment]
Hey, I would want to look into this. Do we have any literature references for this already? 
Either way, I will start reading about this and put here any helpful material that I find.

**Comment by vict0rsch** [comment]
Hey @jaswinder6991, thanks for pitching in :) we're just about to get started on this so there's much to do in scoping said lit. rev. but I'd suggest a couple places to start:

The Goldstein ref on people's savings, and the Chapman ref on climate visuals (see the executive summary in `resourced/outreach`)
