### ISSUE TITLE
Get sample climate data to design relevant backend

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/kdb#33]

**Comment by mukkavilli** [comment]
Global Extreme Sea Level projections
Source: http://data.jrc.ec.europa.eu/dataset/jrc-liscoast-10012

**Comment by mukkavilli** [comment]
**Global Extreme Sea Level projections** 

**File Descriptions:**

_globalTWL_baseline.nc_ contains:
**Total Water Level components - Present day**
100-year event Total Water Level along the global coastline for the period 1980 - 2014, including the 5th, 50th and 95th quantiles. Similar data are included also for the contributing components: mean sea level, tides and extreme weather events (wave setup+storm surge).

_globalTWL_RCP45.nc_ contains:
**Total Water Level components - RCP45 NetCDF**
100-year event Total Water Level along the global coastline for the period 2015 - 2099 under the RCP45 emissions scenario, including the 5th, 50th and 95th quantiles. Similar data are included also for the contributing components: mean sea level, tides and extreme weather events (wave setup+storm surge).

_globalTWL_RCP85.nc_ contains:
**Total Water Level components - RCP85 NetCDF**
100-year event Total Water Level along the global coastline for the period 2015 - 2099 under the RCP85 emissions scenario, including the 5th, 50th and 95th quantiles. Similar data are included also for the contributing components: mean sea level, tides and extreme weather events (wave setup+storm surge).

Download Data:
[Sea level.zip](https://github.com/cc-ai/kdb/files/3125754/Sea.level.zip)

Source: http://data.jrc.ec.europa.eu/dataset/jrc-liscoast-10012

**Comment by vict0rsch** [comment]
http://www.ceda.ac.uk/static/media/uploads/ncas-reading-2015/10_read_netcdf_python.pdf

<blockquote></blockquote>

**Comment by vict0rsch** [comment]
@DatCorno

**Comment by sashavor** [comment]
Use this package to open: https://github.com/Unidata/netcdf4-python
Example: http://schubert.atmos.colostate.edu/~cslocum/netcdf_example.html

<blockquote><img src="https://avatars0.githubusercontent.com/u/613345?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/Unidata/netcdf4-python">Unidata/netcdf4-python</a></strong></div><div>netcdf4-python: python/numpy interface to the netCDF C library - Unidata/netcdf4-python</div></blockquote>
<blockquote><div><strong><a href="http://schubert.atmos.colostate.edu/~cslocum/netcdf_example.html">NetCDF Example | Python | Resources | Slocum</a></strong></div><div>Python - NetCDF reading and writing example with plotting provides
    an example of how to NetCDF with the Python programming language.</div></blockquote>

**Comment by vitoriapacela** [comment]
https://github.com/cc-ai/climate-code/blob/master/data.md

<blockquote><img src="https://avatars3.githubusercontent.com/u/48456149?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/cc-ai/climate-code">cc-ai/climate-code</a></strong></div><div>Code and scripts from the climate science domain. Contribute to cc-ai/climate-code development by creating an account on GitHub.</div></blockquote>
