### ISSUE TITLE
Copyright - Dataset collection

### ISSUE THREAD

**Issue by gcosne** [cc-ai/kdb#54]
**I have read, understand and accept the Terms and conditions**

It is a very good thing to have created a [google form](https://docs.google.com/forms/d/e/1FAIpQLSeN5hzPUkz0_kU5WO2RxO1Bpu7FEKCqVRE-6vSstcJGOZl4aQ/viewform) to collect images but from a legal point of view it would be nice to have the *terms and conditions* of a "public" license such as [Creative Commons : Attribution 4.0 International ](https://creativecommons.org/licenses/by/4.0/legalcode) mentioned in the form.

**What happens if someone uploads an image that does not belong to them?**

I would add a paragraph like : *Submitted photos must be original, created and/or taken by the contestant. It must not contain any materials owned or controlled by a third party for which you have not obtained a license, must not infringe the copyright, trademark, moral rights, rights of privacy/publicity or intellectual property rights of any person or entity.*

**Comment by sashavor** [comment]
I added the paragraph! Thanks :)
