### ISSUE TITLE
Workshop Talks @ CS-Can Student Symposium

### ISSUE THREAD

**Issue by corneauf** [cc-ai/kdb#58]
Date: June 3
Description: [T]he idea of the workshop talks is for them to be somewhat interactive (in any possible way) or perhaps not following (only) a traditional lecture-style presentation. So it would be great if you can have some interaction with the audience or perhaps invite testimonials/stories if applicable (e.g. for the diversity talk from different students representing different minority groups).

The talk is around 45 minutes. Sasha has suggested we divide this time between Sahil, Ayesha and I.

I propose that we start with the more technical stuff with Sahil, then I could explain how we built this and we could end on a high note with Ayesha.

**Comment by ayeshaliaqat** [comment]
Has anyone started slides for this already?

**Comment by vict0rsch** [comment]
Here are a couple starting points:

A draft of my slides for the Geneva presentation ->https://docs.google.com/presentation/d/17Mmt1nb6Nv_AkqZho-QxBQ4HQaKS2eEn5tkqbZ9CRps/edit?usp=sharing

The Mila Template -> https://docs.google.com/presentation/d/1nHUxB7gubqC-GOOpGRoCqAmZ4wV6o4z5pncXfTCWODY/edit#slide=id.p8

<blockquote><img src="https://lh5.googleusercontent.com/aql0QWDVqBfcuTbaOkeh11GY_EvkdY_e4VcuR48zm_YIy4uiZc2vQTqM58nGwYcK9ugJug=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/presentation/d/17Mmt1nb6Nv_AkqZho-QxBQ4HQaKS2eEn5tkqbZ9CRps/edit?usp=sharing&usp=embed_facebook">CCAI @ ITU: AI Commons</a></strong></div><div>Visualizing the consequences of Climate Change Victor Schmidt AI for Social Good Global Submit May, 29th 2019</div></blockquote>
<blockquote><img src="https://lh4.googleusercontent.com/xphKhGLXozr6UnN2uz7o72CZPl3h5SC-dz9kWB4lIgEYhXBFoMbmSmNxSar8SQPxjbcpbQ=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/presentation/d/1nHUxB7gubqC-GOOpGRoCqAmZ4wV6o4z5pncXfTCWODY/edit?usp=embed_facebook">Mila Template</a></strong></div></blockquote>

**Comment by sashavor** [comment]
@DatCorno can you give us an update on this today? The presentation is pretty soon
