### ISSUE TITLE
3-6-12 months timeline

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/kdb#59]
We need to put this timeline together -> sheet?

Or try and use Milestones

**Comment by Vahe987** [comment]
we kind of did for the grant, can use that as a starting point, but go more detailed for close dates, like next 3-4 weeks

**Comment by vict0rsch** [comment]
Yes @Vahe987 that's one of the idea + what do you think about populating these milestones?

* [Summer](https://github.com/cc-ai/kdb/milestone/1)
* [2019](https://github.com/cc-ai/kdb/milestone/2)
* [Year](https://github.com/cc-ai/kdb/milestone/3)

**Comment by Vahe987** [comment]
Summer is pretty populated already, but I think we should go more specific, like June, July, August

**Comment by vict0rsch** [comment]
Or maybe 1 or 2 weeks to sync with meetings ?

**Comment by Vahe987** [comment]
cool, even better, if we can do that, but this is already more like a sprint. To be able to do it, we should understand who is doing what. I have an idea already, but we better talk to be sync

**Comment by Vahe987** [comment]
I had a meeting with Francois and Steven, so will be able to answer timeline questions about this part!

**Comment by vict0rsch** [comment]
cool ; @sashavor can you pu the sheet together and we'll assign roles to that according to pur respective areas?

@Vahe987 we'll chat about this milestone thing

**Comment by sashavor** [comment]
Work in progress here : https://docs.google.com/spreadsheets/d/1GsfFFRahJLg2dt-3ZRmlHH2NojLRnsyA1OwrdDZwuDw/edit?usp=sharing


<blockquote><img src="https://lh5.googleusercontent.com/7sq1BNtZEiEc-tnc1FTDZT92znGbE92_RmtdQ9-7sFJ7KOzBJhwOtHSCn-DjHnIwAGue_A=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/spreadsheets/d/1GsfFFRahJLg2dt-3ZRmlHH2NojLRnsyA1OwrdDZwuDw/edit?usp=sharing&usp=embed_facebook">CCAI-Timeline (Gantt)</a></strong></div><div>Gantt Chart w/ % Complete


2019 CCAI Project Timeline
* = an automatically calculated cell
TASK NAME,START DATE,DAY OF MONTH*,END DATE,DURATION* (WORK DAYS),DAYS COMPLETE*,DAYS REMAINING*,TEAM MEMBER,PERCENT COMPLETE,WEEK 1
May Tasks
Climate Action Fund Proposal,4/29,29,5/13,14,14,0,Sasha,100%
W...</div></blockquote>
