### ISSUE TITLE
Link to website with artist view of floods + slider

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/kdb#61]
Anyone remember this website where they showed views of areas like miami etc. with sliders onto the image like before/after?

If so, can you add it to websites/ux as a link?

**Comment by sashavor** [comment]
https://www.theverge.com/2019/2/17/18223808/climate-change-sea-level-rising-data-visualization-environment
https://ss2.climatecentral.org/#12/40.7298/-74.0070?show=satellite&projections=0-K14_RCP85-SLR&level=5&unit=feet&pois=hide
https://informationisbeautiful.net/visualizations/when-sea-levels-attack-2/
More: https://docs.google.com/spreadsheets/d/18Q3l1B6ZklKiNIiujpLdQA95EKquyOQTJHvSFvFiObs/edit?usp=sharing

<blockquote><img src="https://cdn.vox-cdn.com/thumbor/Xxs8NDUpo-pB0kRuYkaZvm4Ls-k=/0x147:2040x1215/fit-in/1200x630/cdn.vox-cdn.com/assets/2279859/DSC_2320.jpg" width="48" align="right"><div><img src="https://cdn.vox-cdn.com/uploads/chorus_asset/file/7395351/android-chrome-192x192.0.png" height="14"> The Verge</div><div><strong><a href="https://www.theverge.com/2019/2/17/18223808/climate-change-sea-level-rising-data-visualization-environment">Use these tools to help visualize the horror of rising sea levels</a></strong></div><div>Seeing is believing</div></blockquote>
<blockquote><img src="https://infobeautiful4.s3.amazonaws.com/2015/05/main_rising_sea_levels.png" width="48" align="right"><div><img src="/favicon-16x16.png" height="14"> Information is Beautiful</div><div><strong><a href="https://informationisbeautiful.net/visualizations/when-sea-levels-attack-2/">When Sea Levels Attack! — Information is Beautiful</a></strong></div></blockquote>
<blockquote><img src="https://lh5.googleusercontent.com/WMWRbauqpN4q21SiRNGfD--11b1XzcJrrOfUDeNnJg2VeFUXYSUSYFHRQ-15gmi0HiS9oA=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/spreadsheets/d/18Q3l1B6ZklKiNIiujpLdQA95EKquyOQTJHvSFvFiObs/edit?usp=sharing&usp=embed_facebook">Climate Visuals Catalog</a></strong></div><div>reading list

Title,Authors,Link,Tags
“Climate Change” Frames Detection and Categorization Based on Generalized Concepts,Alashri et al.,http://www.worldscientific.com/doi/abs/10.1142/S1793351X16400055,Data Mining; Communication Theory
 (Eds) (2000)Environmental Risks and the Media(London: Routled...</div></blockquote>

**Comment by vict0rsch** [comment]
Nope, none of these :( it's the one where you slide accross images to see, there's like 8 or 10 of them, we shared it a long time ago on slack I think and it was one of the base ideas

**Comment by sashavor** [comment]
I think I found it: https://www.climatecentral.org/news/global-icons-at-risk-from-sea-level-rise-pictures-19633
And the artist's name is Nickolay Lamm (though his website seems to be down: http://nickolaylamm.com/)

<blockquote><img src="https://assets.climatecentral.org/images/made/Mumbai-screenshot_600_315_s_c1_c_c.jpg" width="48" align="right"><div><strong><a href="https://www.climatecentral.org/news/global-icons-at-risk-from-sea-level-rise-pictures-19633">Images Show Impact of Sea Level Rise on Global Icons</a></strong></div><div>Climate Central bridges the scientific community and the public, providing clear information to help people make sound decisions about the climate.</div></blockquote>
<blockquote></blockquote>

**Comment by vict0rsch** [comment]
Yes cool!
