### ISSUE TITLE
Depth Map Prediction from a Single Image

### ISSUE THREAD

**Issue by gcosne** [cc-ai/kdb#66]
**Depth map prediction from a single image :**

 Testing a depth map prediction model from nips 2014 : 
- [paper](https://papers.nips.cc/paper/5539-depth-map-prediction-from-a-single-image-using-a-multi-scale-deep-network.pdf)
- [original project page](https://cs.nyu.edu/~deigen/depth/)
- [pytorch translation of the original code ~medium quality there](https://github.com/zzzyq/Depth-Map-Prediction-with-Multi-Scale-Deep-network.git) 

**To do :**

- Modify the pytorch code, train & evaluate on [kitti dataset](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction)
- Apply to streetview images

**Comment by gcosne** [comment]
Update : Since we want a good model that perform depth-map estimation on street-view like images, we should pick one of the [Kitti benchmark](http://www.cvlibs.net/datasets/kitti/eval_depth.php?benchmark=depth_prediction) with code in the future.

In the meantime we can use : [DenseDepth](https://github.com/ialhashim/DenseDepth/)


![depths_houses](https://user-images.githubusercontent.com/25148268/58486454-e82ba380-8133-11e9-8570-0e1609a15746.png)

Remark : (color of the image is due to a current conversion cv2 -> matplotlib)

**Comment by vict0rsch** [comment]
@sashavor @gcosne @Vahe987 I've explored the megaDepth model and it seems to work well! 

![FireShot Capture 001 -  - ](https://user-images.githubusercontent.com/9283470/58895113-83ec7f00-86f3-11e9-81a8-dcdc8248edce.png)

see infer.py in https://github.com/cc-ai/floods-gans/tree/master/mega_depth

@gcosne is your work with streetview images transferable in anyway here?


<blockquote><img src="https://avatars3.githubusercontent.com/u/48456149?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/cc-ai/floods-gans">cc-ai/floods-gans</a></strong></div><div>Using GANs to simulate how a house would look like, had it suffered from a flood - cc-ai/floods-gans</div></blockquote>

**Comment by sashavor** [comment]
It would be cool to compare the two methods and see if they are
complementary! Looks like this one is maybe more fine grained than the
LIDAR?

**Comment by vict0rsch** [comment]
yeah and more scalable as it does not depend on streetview panoramas

**Comment by sashavor** [comment]
It would be ideal to somehow use both together!

**Comment by Vahe987** [comment]
agree with Sasha, let's compare and use the best or if possible, the combination ...

**Comment by vict0rsch** [comment]
Of course! It's just I'm not fond of the impression I get from the panoramas. We'll see how to combine both approaches in the coming weeks :)

**Comment by vict0rsch** [comment]
If you want to inspect results, download the archive -> https://send.firefox.com/download/729b735a0d5f31f0/#stWvA8HUI4a77czUtXoeyw + open view.html



<blockquote><img src="https://send.firefox.com/send-fb.358d4b57.jpg" width="48" align="right"><div><strong><a href="https://send.firefox.com">Firefox Send</a></strong></div><div>Encrypt and send files with a link that automatically expires to ensure your important documents don’t stay online forever.</div></blockquote>

**Comment by gcosne** [comment]
Panorama are equirectangular spherical image which you can actually map to spherical coordinate. 
I was thinking of extracting the ground plane from the 3D cloud to have an actual height map.

**Question :** how would you extract the ground plane with only depth information ? 

**Remark:** concerning the panoramas we could extract cubic images: ![A test image](https://www.panoramic-photo-guide.com/images/virtual-tour/6-faces-de-cube.jpg)

**Comment by vict0rsch** [comment]
If we start easy and consider the ground to be 1 connex surface in the image, edge detection may do the trick for base case and maybe build from there. Just on the top of my head before any research.

Other idea, map depth pixels to real ones and use segmentation model
