### ISSUE TITLE
Convert binary flooding map (from ICLR article) to pandas dataframe for GAN integration

### ISSUE THREAD

**Issue by sashavor** [cc-ai/kdb#73]
@mukkavilli  will provide data
@vitoriapacela will work on converting it to a format that works with the GANs

**Comment by vitoriapacela** [comment]
https://github.com/cc-ai/climate-code/blob/master/data.md

<blockquote><img src="https://avatars3.githubusercontent.com/u/48456149?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/cc-ai/climate-code">cc-ai/climate-code</a></strong></div><div>Code and scripts from the climate science domain. Contribute to cc-ai/climate-code development by creating an account on GitHub.</div></blockquote>
