### ISSUE TITLE
Make an evaluation procedure for evaluating ML models 

### ISSUE THREAD

**Issue by sashavor** [cc-ai/kdb#79]
Using specific binary criteria (for mask and image)

**Comment by sashavor** [comment]
Convert https://docs.google.com/document/d/1OljHcWYFNRn9v2NpmurjueXJfRhleW6WDYUi5e-F59M/edit to Spreadsheet

<blockquote><img src="https://lh3.googleusercontent.com/Utqf-C9rRQUCbMmNg1DNIJPtrm_osIsc9HWxbgMNuKzN7IYEQm1ieiY3iIpAcHY3vwvmYg=w1200-h630-p" width="48" align="right"><div>Google Docs</div><div><strong><a href="https://docs.google.com/document/d/1OljHcWYFNRn9v2NpmurjueXJfRhleW6WDYUi5e-F59M/edit?usp=embed_facebook">InstaGAN Evaluation</a></strong></div><div>Mask Evaluation : Physics  Appearance of sky, hill, tree etc. Correctness  Road vs Grass        2. Image Evaluation : Water  Texture? Transparency? Color?	 Reflection of objects House Affected or not? Sky Artefacts? Identical? darkened? Rest of the image People Cars Trees           3. Evaluation...</div></blockquote>

**Comment by bsahil29** [comment]
Done.
