### ISSUE TITLE
Write code to filter down mapillary images to relevant ones

### ISSUE THREAD

**Issue by sashavor** [cc-ai/kdb#86]
Initial code is here: https://colab.research.google.com/drive/1ugwkyanAm_NQiFlnuo9h7JTISGeqe9bM

**Comment by gcosne** [comment]
update there : https://github.com/cc-ai/floods-gans/blob/master/various_scripts/mapillary_lib.py

<blockquote><img src="https://avatars3.githubusercontent.com/u/48456149?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/cc-ai/floods-gans">cc-ai/floods-gans</a></strong></div><div>Using GANs to simulate how a house would look like, had it suffered from a flood - cc-ai/floods-gans</div></blockquote>
